### ISSUE TITLE
GripMonke issue

### ISSUE THREAD

**Issue by developer9998** [DeadlyKitten/MonkeModInfo#26]
If you select GripMonke on MMM and then select "View Mod Info" at the bottom it'll bring you to https://github.com/407331629 instead of https://github.com/WowItsKaylie/GripMonke. I think it's because of these two "Git Path" lines being just a set of random numbers in mods.json and modinfo.json.
![image](https://user-images.githubusercontent.com/81720436/170839366-009fa310-e3d0-45da-b771-8b761933545b.png)
![image](https://user-images.githubusercontent.com/81720436/170839379-59867740-d4c1-4006-a2a9-3c0f43a024ec.png)

**Comment by burritosoftware** [comment]
Fixed, thanks and sorry for the delay
